//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ModelFirstName {
            get {
                return ResourceManager.GetString("ModelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string ModelGender {
            get {
                return ResourceManager.GetString("ModelGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ModelLastName {
            get {
                return ResourceManager.GetString("ModelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ModelPassword {
            get {
                return ResourceManager.GetString("ModelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ModelPasswordConfirm {
            get {
                return ResourceManager.GetString("ModelPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ViewLoginBtnLogin {
            get {
                return ResourceManager.GetString("ViewLoginBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create My Account.
        /// </summary>
        public static string ViewSignBtnCreateAccount {
            get {
                return ResourceManager.GetString("ViewSignBtnCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string ViewSignFemale {
            get {
                return ResourceManager.GetString("ViewSignFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string ViewSignMale {
            get {
                return ResourceManager.GetString("ViewSignMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gender.
        /// </summary>
        public static string ViewSignNoGender {
            get {
                return ResourceManager.GetString("ViewSignNoGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up with facebook.
        /// </summary>
        public static string ViewSignTitleFacebook {
            get {
                return ResourceManager.GetString("ViewSignTitleFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be connected on the Facebook..
        /// </summary>
        public static string YouMustFacebookConect {
            get {
                return ResourceManager.GetString("YouMustFacebookConect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert your password.
        /// </summary>
        public static string YouMustSpecifyPassword {
            get {
                return ResourceManager.GetString("YouMustSpecifyPassword", resourceCulture);
            }
        }
    }
}
